"""main.py: Entry point for Code Sentry AI Security Code Reviewer.

Takes a user query and a code snippet, configures the Gemini LLM with the security
expert system prompt, and provides the local `scan_vulnerabilities` tool via the
Google Gen AI SDK's automatic function calling.
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Any, Callable, Dict, Optional, Tuple

from prompts import SYSTEM_PROMPT
from tools import scan_vulnerabilities

# Ensure UTF-8 output encoding across Windows/Linux terminals
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Global tracker to observe if the model triggered the local tool during execution
_TOOL_INVOCATION_LOG: list[dict[str, Any]] = []


def instrumented_scan_vulnerabilities(code_snippet: str, language: str = "python") -> dict:
    """Wrapper around scan_vulnerabilities that logs invocation telemetry for auditability."""
    result = scan_vulnerabilities(code_snippet=code_snippet, language=language)
    _TOOL_INVOCATION_LOG.append({
        "tool": "scan_vulnerabilities",
        "language": language,
        "snippet_length": len(code_snippet),
        "total_findings": result.get("total_findings", 0),
        "findings": result.get("findings", []),
    })
    return result


def format_user_prompt(query: str, code_snippet: str, language: str = "python") -> str:
    """Formats the user query and code snippet into a standardized prompt."""
    return f"""### User Query:
{query}

### Code Snippet (Language: {language}):
```{language}
{code_snippet}
```

Please review the code snippet, invoke `scan_vulnerabilities` if potentially risky patterns are detected, and provide your structured security evaluation.
"""


def run_with_gemini(
    query: str,
    code_snippet: str,
    language: str = "python",
    model: str = "gemini-2.5-flash",
    api_key: Optional[str] = None,
) -> Tuple[str, bool]:
    """Runs the code review using Google Gen AI SDK with automatic tool invocation.

    Returns:
        Tuple of (response_text, tool_was_invoked_boolean)
    """
    try:
        from google import genai
        from google.genai import types
    except ImportError:
        raise RuntimeError(
            "The google-genai SDK is not installed. Run: pip install google-genai"
        )

    resolved_api_key = api_key or os.environ.get("GEMINI_API_KEY")
    if not resolved_api_key:
        raise ValueError(
            "GEMINI_API_KEY environment variable is not set. "
            "Please export GEMINI_API_KEY='your-key' or pass --api-key. "
            "Alternatively, use --mock to run in offline test mode."
        )

    _TOOL_INVOCATION_LOG.clear()

    client = genai.Client(api_key=resolved_api_key)
    prompt = format_user_prompt(query, code_snippet, language)

    config = types.GenerateContentConfig(
        system_instruction=SYSTEM_PROMPT,
        tools=[instrumented_scan_vulnerabilities],
        temperature=0.2,
    )

    try:
        response = client.models.generate_content(
            model=model,
            contents=prompt,
            config=config,
        )
        tool_invoked = len(_TOOL_INVOCATION_LOG) > 0
        return response.text or "No response generated by model.", tool_invoked
    except Exception as e:
        error_msg = f"Gemini API Error: {type(e).__name__} - {str(e)}"
        return error_msg, False


def run_mock_agent(
    query: str,
    code_snippet: str,
    language: str = "python",
) -> Tuple[str, bool]:
    """Simulates agent evaluation for offline testing and verification.

    Decides dynamically whether to invoke scan_vulnerabilities based on snippet
    patterns, runs the tool, and constructs the structured response according
    to the prompt specification.
    """
    _TOOL_INVOCATION_LOG.clear()

    # Heuristic for mock mode decision (mirrors model decision boundary)
    risky_indicators = [
        "select", "insert", "update", "delete", "cursor", "db", "query",
        "eval", "exec", "subprocess", "os.system", "pickle", "yaml",
        "password", "secret", "token", "key", "api", "open", "hashlib",
        "md5", "sha1", "request",
    ]
    lower_snippet = code_snippet.lower()
    has_risky_surface = any(term in lower_snippet for term in risky_indicators)

    tool_invoked = False
    findings_data = None

    if has_risky_surface:
        tool_invoked = True
        findings_data = instrumented_scan_vulnerabilities(code_snippet, language)

    # Format structured output
    output_lines = []
    if tool_invoked and findings_data and findings_data["total_findings"] > 0:
        verdict = findings_data.get("verdict_suggestion", "HIGH RISK")
        output_lines.append(f"## 1. Summary Verdict\n**{verdict}**: Potentially critical security vulnerabilities were discovered during the security assessment. This code should NOT be deployed to production in its current form.\n")
        output_lines.append("## 2. Findings & Risk Analysis")
        for i, f in enumerate(findings_data["findings"], 1):
            output_lines.append(
                f"### Finding #{i}: [{f['severity']}] {f['category']}\n"
                f"- **Line Reference**: Line {f['line_number']} (`{f['line_content']}`)\n"
                f"- **Plain-Language Explanation**: {f['description']}\n"
                f"- **Recommended Fix**: {f['recommendation']}\n"
            )
        output_lines.append("## 3. Remediated Code")
        output_lines.append("```python\n# Remediated secure version:\n# Ensure all external inputs are parameterized, validate paths,\n# and load secrets securely from environment variables.\n```\n")
        output_lines.append("## 4. Key Takeaways\n- Always separate code from untrusted data (use parameterized queries and arguments).\n- Never store hardcoded secrets or passwords in source files.\n- Replace obsolete cryptography (MD5/SHA1) and unsafe serialization (pickle).")
    else:
        output_lines.append("## 1. Summary Verdict\n**SAFE**: No security vulnerabilities or unsafe coding patterns were detected. The snippet appears clean and benign.\n")
        output_lines.append("## 2. Findings & Risk Analysis\nNo findings. The provided implementation does not perform risky I/O, execute external processes, evaluate dynamic code, or process untrusted inputs without validation.\n")
        output_lines.append("## 3. Remediated Code\nNo remediation required. The original implementation adheres to safe programming standards.\n")
        output_lines.append("## 4. Key Takeaways\n- Maintain unit test coverage for edge cases.\n- Continue adhering to clean coding standards.")

    return "\n".join(output_lines), tool_invoked


def review_code(
    query: str,
    code_snippet: str,
    language: str = "python",
    model: str = "gemini-2.5-flash",
    mock: bool = False,
    api_key: Optional[str] = None,
) -> None:
    """Executes the security review workflow and prints formatted results."""
    print("=" * 80)
    print("[*] CODE SENTRY - AI SECURITY CODE REVIEWER")
    print("=" * 80)
    print(f"[*] User Query: {query}")
    print(f"[*] Language  : {language}")
    print(f"[*] Mode      : {'Mock / Offline' if mock else f'Google Gemini ({model})'}")
    print("-" * 80)
    print("[*] Code Snippet to Review:")
    for idx, line in enumerate(code_snippet.splitlines(), start=1):
        print(f"  {idx:3d} | {line}")
    print("-" * 80)
    print("[*] Running security analysis...")

    if mock:
        response_text, tool_invoked = run_mock_agent(query, code_snippet, language)
    else:
        try:
            response_text, tool_invoked = run_with_gemini(
                query=query,
                code_snippet=code_snippet,
                language=language,
                model=model,
                api_key=api_key,
            )
        except Exception as e:
            print(f"\n[!] Error during review execution: {e}")
            print("\n[i] Tip: To run without an active Gemini API key, use the --mock flag.")
            return

    print("\n" + "=" * 80)
    print("[*] SECURITY REVIEW REPORT")
    print("=" * 80)
    tool_status = "CALLED [YES]" if tool_invoked else "SKIPPED [NO] (clean code)"
    print(f"[*] Tool Invocation: scan_vulnerabilities was {tool_status}")
    if tool_invoked and _TOOL_INVOCATION_LOG:
        findings_count = _TOOL_INVOCATION_LOG[0].get("total_findings", 0)
        print(f"    -> Tool reported: {findings_count} finding(s)")
    print("-" * 80)
    print(response_text)
    print("=" * 80 + "\n")


def parse_arguments() -> argparse.Namespace:
    """Parses command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Code Sentry: AI-Powered Security Code Reviewer using Google Gen AI SDK."
    )
    parser.add_argument(
        "--query", "-q",
        type=str,
        default="Is this function safe to use in production?",
        help="Natural language user question/query regarding the code.",
    )
    parser.add_argument(
        "--snippet", "-s",
        type=str,
        help="Code snippet passed as a string.",
    )
    parser.add_argument(
        "--file", "-f",
        type=str,
        help="Path to file containing the code snippet to review.",
    )
    parser.add_argument(
        "--language", "-l",
        type=str,
        default="python",
        help="Programming language hint (default: python).",
    )
    parser.add_argument(
        "--model", "-m",
        type=str,
        default=os.environ.get("GEMINI_MODEL", "gemini-2.5-flash"),
        help="Gemini model name (default: gemini-2.5-flash).",
    )
    parser.add_argument(
        "--api-key",
        type=str,
        help="Gemini API Key (optional, defaults to GEMINI_API_KEY env var).",
    )
    parser.add_argument(
        "--mock",
        action="store_true",
        help="Run in offline mock mode (useful for testing without API key).",
    )
    parser.add_argument(
        "--interactive", "-i",
        action="store_true",
        help="Run in interactive CLI mode.",
    )
    return parser.parse_args()


def interactive_mode(args: argparse.Namespace) -> None:
    """Runs Code Sentry interactively from terminal."""
    print("=" * 80)
    print("🛡️  Welcome to Code Sentry Interactive Security Reviewer")
    print("=" * 80)
    while True:
        try:
            query = input("\nEnter your query (or 'quit' to exit) [default: Is this function safe?]: ").strip()
            if query.lower() in ("quit", "exit", "q"):
                print("Exiting Code Sentry. Stay safe!")
                break
            if not query:
                query = "Is this function safe to use in production?"

            print("Enter code snippet (type 'END' on a new line when finished):")
            lines = []
            while True:
                line = input()
                if line.strip() == "END":
                    break
                lines.append(line)
            snippet = "\n".join(lines)

            if not snippet.strip():
                print("⚠️  No code provided. Please try again.")
                continue

            review_code(
                query=query,
                code_snippet=snippet,
                language=args.language,
                model=args.model,
                mock=args.mock,
                api_key=args.api_key,
            )
        except (KeyboardInterrupt, EOFError):
            print("\nSession ended.")
            break


def main() -> None:
    """Main CLI entry point."""
    args = parse_arguments()

    if args.interactive:
        interactive_mode(args)
        return

    # Determine snippet source
    snippet = ""
    if args.snippet:
        snippet = args.snippet
    elif args.file:
        if not os.path.exists(args.file):
            print(f"❌ Error: File not found: {args.file}")
            sys.exit(1)
        with open(args.file, "r", encoding="utf-8") as f:
            snippet = f.read()
    else:
        # If neither provided and not interactive, show default example
        snippet = """def fetch_user(user_id):
    query = f"SELECT * FROM users WHERE id = '{user_id}'"
    cursor.execute(query)
    return cursor.fetchone()
"""
        print("ℹ️  No snippet provided via --snippet or --file. Running on default sample snippet.\n")

    review_code(
        query=args.query,
        code_snippet=snippet,
        language=args.language,
        model=args.model,
        mock=args.mock,
        api_key=args.api_key,
    )


if __name__ == "__main__":
    main()
